export WORKSPACE=/home/pings/projects/cangjie-resumptions
export OPENSSL_PATH=/usr/lib/x86_64-linux-gnu;
export LD_LIBRARY_PATH=$OPENSSL_PATH:$LD_LIBRARY_PATH
export PATH=/usr/lib/llvm-15/bin:$PATH; 
export ARCH=x86_64 
export SDK_NAME=linux-x64
export CANGJIE_VERSION=1.0.0
export STDX_VERSION=1
export CANGJIE_STDX_PATH=$WORKSPACE/software/linux_x86_64_cjnative/static/stdx
source $WORKSPACE/software/cangjie/envsetup.sh
cjpm build