package cangjie_experiments

import cangjie_experiments.side_effects.fs.*
import cangjie_experiments.side_effects.collections.*
import cangjie_experiments.side_effects.database.*
import cangjie_experiments.side_effects.io.*
import cangjie_experiments.side_effects.net.*

main() {
    println("Starting main")
    // main_collections_testing()
    main_fs_testing()
    // main_net_testing()
    // main_io_testing()
    // main_database_testing()
}